### PR TITLE
Fix typos in PBS 122

### PR DESCRIPTION
**Pull request by steinbil**
Fixed two typos in PBS 122.

PS.
Don't know why git diff is showing the last paragraph is changed. It looks unchanged to me, and any possible change was unintentional. Could it be a newline thing?

PPS.
I hope I'm doing this right. I'm not sure why me merging the master branch into my fix-typos branch shows up as a separate commit in the pull request - this should already exist in the master branch, no?

### CODE REVIEW

**Comment by steinbil** [comment]
Maybe I should have created a new branch for the new fixes after the last pull request was merged, instead of working on the same branch? Let me know if I need to do this again from a new branch...

**Comment by NosillaCast** [comment]
As new as you are to this, I'm just as new at approving pull requests @steinbil! I would have sworn I accepted and merged the pull request last week, but when I came back here it was still asking me if I wanted to merge. I definitely did it this time and I can see:

`NosillaCast merged commit e1dbe22 into bartificer: master 35 seconds ago`

so hopefully you can see it now?

**Comment by steinbil** [comment]
> As new as you are to this, I'm just as new at approving pull requests @steinbil! I would have sworn I accepted and merged the pull request last week...

I did submit a different pull request a couple of days ago with a branch of the same name, that might be the reason. I just hope I'm doing it right!

**Comment by NosillaCast** [comment]
well that might explain part of the mystery! I also thought I confirmed that the typos were fixed locally last time. Can you confirm that they're fixed locally for you after you pull?

**Comment by steinbil** [comment]
Yes! I can confirm that the changes i suggested to pbs3.md and pbs122.md are updated locally after pulling from the master branch. It's nice to be able to contribute, I'll keep looking for typos as I go through the tutorials!

**Comment by NosillaCast** [comment]
Excellent! Please do keep contributing, it really helps. Bart proofreads, I proofread, Helma runs it through Grammarly, and we STILL find errors!

**Pull request merged**
