### PR TITLE
Fixed typos in pbs5.md and corresponding pbs5b.zip

### PR DESCRIPTION
**Pull request by steinbil**
Found and fixed a few typos in PBS 5.
Since some of the typos were in the HTML example file, I had to fix them twice: once in the pbs5.md file in the example code tag and once in the index.html file contained within the pbs5b.zip file. I just unzipped, fixed the typos, and rezipped the files.

### CODE REVIEW

**Comment by NosillaCast** [comment]
I think you're starting to add your own writing style and it's going to be a TON of work on my part to parse through these. Can we stick to pure typos, please? Like "able" needed to be fixed, but you added the word "some" (and set the commit message to say "only" was missing.)

I'm going to change that one typo on my own and now figure out how to refuse the commit.

**Comment by steinbil** [comment]
Sorry about the wrong word in the commit message! And I can see the argument that the syntax/punctuation is about writing style, I won't suggest more of those.

But adding the word "some" is really NOT about writing style - the way it was written makes no sense at all: "All images should have alt text, but only images need titles." 

There was also the "Exmaple" typo in both the md-file and the index.html in the zip-file.

**Comment by steinbil** [comment]
Let me know if you want me to make a new pull request fixing the typos + the word "some", and leaving the syntax/punctuation alone.

**Comment by NosillaCast** [comment]
@steinbil thanks - I did see it. I'm trying to figure out how to strike a balance between loving your enthusiasm and finding fixing typos so exhausting! For every one you find, I have to pull your changes, run a comparison between the files, decide which ones I agree with, accept what I do, and not what I don't and also pull the new version to my own computer. It's about a half-hour of work for every pull request! I really do appreciate the findings though.

**Comment by NosillaCast** [comment]
It's possible I successfully merged your pull request in!

**Comment by steinbil** [comment]
Great! I'll try to be a bit more judicial and explicit in the future, so you won't have too much on your hands. And of course, take your time going through them. I'll keep adding, sparingly, pull request for the most important/obvious fixes.

Btw - please let me know if it would be easier if I grouped more commits together in a bigger pull request, or if you want few commits per pull request, I don't know what's more efficient (but I did learn to keep the commits clean/specific).

**Comment by NosillaCast** [comment]
Sounds good, thanks for undertstanding. I think giving me all fixes for one post in one commit is best. The annoying thing is if the fix is also in the zip file, because Git can't tell me what changes have been made. I have to make a copy of the zip, unpack it elsewhere on my computer, then flip back and forth on what the change was and find it in the zip by hand!

**Pull request merged**
